# Generated by Django 5.2.11 on 2026-08-20 08:38

import apps.common.fields
import django.db.models.deletion
import jdatetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('production', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='شماره سفارش')),
                ('created_at', apps.common.fields.PersianDateField(default=jdatetime.date.today, verbose_name='تاریخ سفارش')),
                ('due_date', apps.common.fields.PersianDateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'بسیار بالا'), (2, 'بالا'), (3, 'متوسط'), (4, 'پایین')], default=3, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('planned', 'برنامه\u200cریزی شده'), ('producing', 'در حال تولید'), ('completed', 'تکمیل شده'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ نهایی')),
                ('shipping_address', models.TextField(verbose_name='آدرس ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('paid_at', apps.common.fields.PersianDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.customer', verbose_name='مشتری')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نماینده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='اندازه')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لیست سفارش',
                'verbose_name_plural': 'لیست سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, verbose_name='قطعه')),
                ('code', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('جناغی', 'جناغی'), ('بتنی', 'بتنی')], max_length=20, verbose_name='کد رنگ')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordercolor', to='orders.orderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'رنگ سفارش',
                'verbose_name_plural': 'رنگ\u200cهای سفارش',
                'unique_together': {('orderitem', 'part')},
            },
        ),
        migrations.CreateModel(
            name='PackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('unit_number', models.PositiveIntegerField(verbose_name='شماره واحد')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='packaging_qr/')),
                ('is_packed', models.BooleanField(default=False, verbose_name='بسته\u200cبندی شده')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('packed_at', apps.common.fields.PersianDateTimeField(blank=True, null=True, verbose_name='زمان بسته\u200cبندی')),
                ('shipped_at', apps.common.fields.PersianDateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_units', to=settings.AUTH_USER_MODEL, verbose_name='بسته\u200cبندی\u200cکننده')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_units', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'واحد بسته\u200cبندی',
                'verbose_name_plural': 'واحدهای بسته\u200cبندی',
                'ordering': ['order_item', 'unit_number'],
                'unique_together': {('order_item', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('station_name', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='ایستگاه کاری')),
                ('step_order', models.PositiveIntegerField(verbose_name='اولویت مرحله')),
                ('quantity', models.PositiveIntegerField(verbose_name='عدد قطعه')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار مرحله قبل'), ('pending', 'آماده انجام'), ('done', 'تکمیل شده')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('completed_at', apps.common.fields.PersianDateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('color_part', models.CharField(blank=True, max_length=50, verbose_name='بخش رنگی')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع برنامه\u200cریزی شده')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان برنامه\u200cریزی شده')),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='کارگر تخصیص\u200cیافته')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orders.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_tasks', to='orders.orderitem', verbose_name='آیتم سفارش مرتبط')),
                ('painting_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.paintingstage', verbose_name='مرحله نقاشی')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.part', verbose_name='قطعه')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
            ],
            options={
                'verbose_name': 'وظیفه تولید',
                'verbose_name_plural': 'وظایف تولید',
                'ordering': ['order', 'step_order'],
                'indexes': [models.Index(fields=['station_name', 'scheduled_start'], name='orders_prod_station_42eba3_idx'), models.Index(fields=['assigned_worker', 'scheduled_start'], name='orders_prod_assigne_9a27ab_idx'), models.Index(fields=['order_item', 'station_name', 'status'], name='orders_prod_order_i_a3e7e5_idx')],
            },
        ),
    ]
