# Generated by Django 5.2.11 on 2026-08-20 08:43

import apps.common.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('stage', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='مرحله')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('created_at', apps.common.fields.PersianDateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش تولید',
                'verbose_name_plural': 'گزارش\u200cهای تولید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('plate_number', models.CharField(max_length=50, verbose_name='پلاک')),
                ('shipped_at', apps.common.fields.PersianDateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('packaging_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_logs', to='orders.packagingunit', verbose_name='بسته\u200cبندی')),
                ('shipped_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
            ],
            options={
                'verbose_name': 'بارگیری',
                'verbose_name_plural': 'بارگیری',
                'ordering': ['-shipped_at'],
            },
        ),
    ]
