# Generated by Django 5.2.17 on 2026-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='طول سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)'),
        ),
    ]
