# Generated by Django 5.2.11 on 2026-08-20 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ تعطیلی')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='مناسبت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تعطیلی',
                'verbose_name_plural': 'تعطیلات',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PaintingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام روند')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد روند')),
                ('color_codes', models.JSONField(default=list, verbose_name='لیست کدهای رنگی مرتبط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'روند نقاشی',
                'verbose_name_plural': 'روندهای نقاشی',
            },
        ),
        migrations.CreateModel(
            name='PaintingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ترتیب مرحله')),
                ('name', models.CharField(max_length=100, verbose_name='نام مرحله')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='زمان انجام (دقیقه)')),
                ('drying_time_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان خشک\u200cشدن (دقیقه)')),
                ('required_skill', models.CharField(default='painter', max_length=50, verbose_name='مهارت مورد نیاز')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='production.paintingprocess')),
            ],
            options={
                'verbose_name': 'مرحله نقاشی',
                'verbose_name_plural': 'مراحل نقاشی',
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'order')},
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('stage', models.CharField(choices=[('cut', 'برش'), ('cnc', 'CNC'), ('dr', 'سوراخکاری'), ('pvc', 'نوارکاری'), ('prs', 'پرس'), ('mon', 'مونتاژ اول'), ('vacum', 'وکیوم'), ('paint', 'نقاشی'), ('assembly2', 'مونتاژ نهایی'), ('packaging', 'بسته\u200cبندی'), ('shipping', 'ارسال شده')], max_length=50, verbose_name='مرحله کاری')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='مهارت\u200cها (لیست رشته\u200cها)')),
                ('skill_priority', models.JSONField(blank=True, default=dict, verbose_name='اولویت/میزان مهارت کارگر')),
                ('is_available', models.BooleanField(default=True, verbose_name='فعال برای زمان\u200cبندی')),
                ('work_start', models.TimeField(default=django.utils.timezone.now, verbose_name='شروع کار')),
                ('work_end', models.TimeField(default=django.utils.timezone.now, verbose_name='پایان کار')),
                ('break_start', models.TimeField(default=django.utils.timezone.now, verbose_name='شروع استراحت')),
                ('break_end', models.TimeField(default=django.utils.timezone.now, verbose_name='پایان استراحت')),
                ('excluded_products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='محصولات ممنوعه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کارگر',
                'verbose_name_plural': 'پروفایل کارگران',
            },
        ),
        migrations.CreateModel(
            name='PaintingAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('color_codes', models.JSONField(blank=True, help_text='لیست کدهای رنگی که این قانون برای آن\u200cها اعمال می\u200cشود (خالی = همه رنگ\u200cها)', null=True, verbose_name='کدهای رنگ')),
                ('rule_type', models.CharField(choices=[('priority', 'فقط اولویت\u200cدهی'), ('exclusive', 'محدودکننده'), ('exclusion', 'منع\u200cکننده')], default='priority', max_length=20, verbose_name='نوع قانون')),
                ('priority', models.IntegerField(default=100, help_text='عدد بالاتر = اولویت بیشتر در زمان\u200cبندی (فقط برای نوع اولویت\u200cدهی)', verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.paintingprocess', verbose_name='روند نقاشی (اختیاری)')),
                ('painting_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.paintingstage', verbose_name='مرحله نقاشی (اختیاری)')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='production.workerprofile', verbose_name='کارگر')),
            ],
            options={
                'verbose_name': 'قانون تخصیص کارگر',
                'verbose_name_plural': 'قوانین تخصیص کارگر',
                'ordering': ['-priority', 'worker'],
            },
        ),
    ]
