# Generated by Django 5.2.17 on 2026-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='طول سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض سفارشی (سانتی\u200cمتر)'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت واحد'),
        ),
    ]
