# Generated by Django 5.2.11 on 2026-08-20 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن')),
                ('template_type', models.CharField(choices=[('welcome', 'خوش\u200cآمدگویی'), ('order_confirmation', 'تایید سفارش'), ('payment_success', 'موفقیت پرداخت'), ('password_reset', 'بازنشانی رمز عبور')], max_length=50, verbose_name='نوع')),
            ],
            options={
                'verbose_name': 'قالب ایمیل',
                'verbose_name_plural': 'قالب\u200cهای ایمیل',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notification_type', models.CharField(choices=[('email', 'ایمیل'), ('sms', 'پیامک'), ('push', 'پوش')], max_length=20, verbose_name='نوع')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
