# Generated by Django 4.2.30 on 2026-08-22 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام رنگ')),
                ('code', models.CharField(blank=True, max_length=7, verbose_name='کد رنگ (هگز)')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام ورق')),
                ('thickness', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='ضخامت (میلی\u200cمتر)')),
            ],
            options={
                'verbose_name': 'متریال',
                'verbose_name_plural': 'متریال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه')),
                ('length', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='طول (X)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='عرض (Y)')),
                ('grain', models.CharField(blank=True, max_length=100, verbose_name='دسته')),
                ('pname', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('turn', models.BooleanField(default=False, verbose_name='چرخش')),
                ('f26', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F26')),
                ('f18', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F18')),
                ('f4', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F4')),
                ('f5', models.CharField(blank=True, max_length=100, verbose_name='نوار لبه F5')),
                ('f3', models.CharField(blank=True, max_length=100, verbose_name='بارکد F3')),
                ('f2', models.CharField(blank=True, max_length=100, verbose_name='نام قطعه F2')),
                ('routing_code', models.CharField(max_length=255, verbose_name='تحویل به مرحله')),
                ('base_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='catalog.part', verbose_name='قطعه پایه')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.material', verbose_name='متریال')),
            ],
            options={
                'verbose_name': 'قطعه تولید',
                'verbose_name_plural': 'قطعات تولید',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('default_size', models.CharField(blank=True, max_length=100, verbose_name='سایز پیش\u200cفرض')),
                ('default_colors', models.JSONField(blank=True, default=dict, verbose_name='رنگ\u200cهای پیش\u200cفرض')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت پایه')),
                ('price_increment_per_cm', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='افزایش قیمت به ازای هر سانتی\u200cمتر')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='طول (سانتی\u200cمتر)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض (سانتی\u200cمتر)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع (سانتی\u200cمتر)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('parts_list_key', models.CharField(blank=True, max_length=255, verbose_name='مسیر فایل')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=100, verbose_name='نام قسمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزء محصول',
                'verbose_name_plural': 'اجزای محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='دسته'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('length', models.PositiveIntegerField(verbose_name='طول (سانتی\u200cمتر)')),
                ('width', models.PositiveIntegerField(verbose_name='عرض (سانتی\u200cمتر)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='catalog.productsection', verbose_name='جزء محصول')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد در هر محصول')),
                ('color_part', models.CharField(blank=True, max_length=20, null=True, verbose_name='بخش رنگی')),
                ('allow_material_override', models.BooleanField(default=False, verbose_name='امکان تغییر متریال با رنگ')),
                ('color_material_map', models.JSONField(blank=True, default=dict, verbose_name='نگاشت رنگ به متریال')),
                ('size_affected', models.BooleanField(default=False, verbose_name='تحت تأثیر اندازه')),
                ('size_adjustment_rule', models.CharField(blank=True, max_length=100, verbose_name='قانون تغییر اندازه')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='catalog.product')),
            ],
            options={
                'verbose_name': 'فرمول ساخت',
                'verbose_name_plural': 'فرمول\u200cهای ساخت',
                'unique_together': {('product', 'part')},
            },
        ),
    ]
