# Generated by Django 5.2.17 on 2026-08-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productreview_image_comparisonlist_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.color', verbose_name='رنگ'),
        ),
    ]
