# Generated by Django 5.2.17 on 2026-08-23 11:43

from django.db import migrations, models


def copy_price_increment_to_percent(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        product.length_price_percent = product.price_increment_per_cm
        product.width_price_percent = product.price_increment_per_cm
        product.height_price_percent = product.price_increment_per_cm
        product.save(update_fields=['length_price_percent', 'width_price_percent', 'height_price_percent'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر ارتفاع توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی‌متر ارتفاع'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر طول توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی‌متر طول'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_editable',
            field=models.BooleanField(default=True, verbose_name='امکان تغییر عرض توسط مشتری'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد افزایش قیمت به ازای هر سانتی‌متر عرض'),
        ),
        migrations.RunPython(copy_price_increment_to_percent, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='price_increment_per_cm',
        ),
    ]