# Generated by Django 5.2.17 on 2026-08-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_price_increment_per_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='material_override',
            field=models.BooleanField(default=False, verbose_name='متریال به\u200cصورت دستی تعیین شده (نادیده گرفتن نگاشت خودکار)'),
        ),
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد در هر محصول'),
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.productsection', verbose_name='جزء محصول (والد)'),
        ),
        migrations.CreateModel(
            name='ColorMaterialMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_material_maps', to='catalog.productcategory', verbose_name='دسته\u200cبندی (اختیاری — خالی یعنی برای همه دسته\u200cها)')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_maps', to='catalog.color', verbose_name='رنگ')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_maps', to='catalog.material', verbose_name='متریال پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'نگاشت رنگ به متریال',
                'verbose_name_plural': 'نگاشت\u200cهای رنگ به متریال',
                'unique_together': {('color', 'category')},
            },
        ),
    ]
