# Generated by Django 5.2.17 on 2026-08-23 15:32
from django.db import migrations


def migrate_bom_to_part_section(apps, schema_editor):
    ProductBOM = apps.get_model('catalog', 'ProductBOM')
    Part = apps.get_model('catalog', 'Part')
    ProductSection = apps.get_model('catalog', 'ProductSection')

    for bom in ProductBOM.objects.select_related('part', 'product').all():
        part = bom.part
        if part.section_id:
            continue

        section = None
        if bom.color_part:
            section = ProductSection.objects.filter(
                product=bom.product,
                name__iexact=bom.color_part
            ).first()

        if not section:
            section = ProductSection.objects.filter(product=bom.product).first()

        if section:
            part.section = section
            part.save(update_fields=['section'])

        if part.quantity == 1 and bom.quantity and bom.quantity != 1:
            part.quantity = bom.quantity
            part.save(update_fields=['quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_part_material_override_part_quantity_part_section_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_bom_to_part_section, reverse_code=migrations.RunPython.noop),
    ]
