# Generated by Django 5.2.17 on 2026-08-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_migrate_bom_to_part_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbom',
            name='allow_material_override',
        ),
        migrations.RemoveField(
            model_name='productbom',
            name='color_material_map',
        ),
        migrations.RemoveField(
            model_name='productbom',
            name='color_part',
        ),
    ]
