# Generated by Django 5.2.11 on 2026-08-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_piece'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colormaterialmap',
            unique_together={('color',)},
        ),
        migrations.AddField(
            model_name='productbom',
            name='allow_material_override',
            field=models.BooleanField(default=False, verbose_name='اجازه تغییر متریال بر اساس رنگ'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='color_material_map',
            field=models.JSONField(blank=True, default=dict, verbose_name='نگاشت رنگ به متریال'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='color_part',
            field=models.CharField(blank=True, max_length=20, verbose_name='بخشی که رنگ آن قابل تغییر است'),
        ),
        migrations.AlterField(
            model_name='colormaterialmap',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_mappings', to='catalog.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='colormaterialmap',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.material', verbose_name='متریال'),
        ),
        migrations.RemoveField(
            model_name='colormaterialmap',
            name='category',
        ),
    ]
