# Generated by Django 5.2.17 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_bom_material_override_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbom',
            name='allow_material_override',
        ),
        migrations.RemoveField(
            model_name='productbom',
            name='color_material_map',
        ),
        migrations.RemoveField(
            model_name='productbom',
            name='color_part',
        ),
    ]
