# Generated by Django 5.2.11 on 2026-08-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_deprecated_bom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbom',
            name='allow_material_override',
            field=models.BooleanField(default=False, verbose_name='امکان تغییر متریال با رنگ'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='color_material_map',
            field=models.JSONField(blank=True, default=dict, verbose_name='نگاشت رنگ به متریال'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='color_part',
            field=models.CharField(blank=True, choices=[('بدنه', 'بدنه'), ('درب', 'درب'), ('دستگیره', 'دستگیره'), ('پایه', 'پایه'), ('صفحه', 'صفحه'), ('رینگ', 'رینگ')], max_length=20, null=True, verbose_name='بخش رنگی'),
        ),
        migrations.AlterField(
            model_name='productbom',
            name='size_adjustment_rule',
            field=models.CharField(blank=True, help_text='مثال: length+length_diff, width/3', max_length=100, verbose_name='قانون تغییر اندازه'),
        ),
    ]
