# Generated by Django 5.2.11 on 2026-08-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productbom_allow_material_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='section',
        ),
        migrations.RemoveField(
            model_name='part',
            name='material_override',
        ),
        migrations.DeleteModel(
            name='ProductSection',
        ),
    ]
