# Generated by Django 5.2.11 on 2026-08-27 06:20

from django.db import migrations
from django.utils.text import slugify


def seed_categories(apps, schema_editor):
    ProductCategory = apps.get_model('catalog', 'ProductCategory')
    categories = [
        'کمد',
        'دراور',
        'شلف',
        'جاکفشی',
        'باکس',
        'کمپ',
        'اکسسوری',
        'آباژور',
        'اداری',
    ]
    for name in categories:
        slug = slugify(name, allow_unicode=True)
        obj, created = ProductCategory.objects.get_or_create(
            slug=slug,
            defaults={'name': name},
        )
        if not created:
            obj.name = name
            obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_part_section_remove_part_material_override_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=migrations.RunPython.noop),
    ]
