# Generated by Django 5.2.11 on 2026-09-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbom',
            name='width_adjustment_rule',
            field=models.CharField(blank=True, help_text='مثال: width+width_diff, width/3', max_length=100, verbose_name='قانون تغییر عرض'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='width_affected',
            field=models.BooleanField(default=False, verbose_name='تحت تأثیر عرض'),
        ),
    ]
