# Generated by Django 5.2.11 on 2026-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productbom_width_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='ارتفاع (Z)'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='height_adjustment_rule',
            field=models.CharField(blank=True, help_text='مثال: length+height_diff, width/2 (از height_diff در فرمول استفاده کنید)', max_length=100, verbose_name='قانون تغییر ارتفاع'),
        ),
        migrations.AddField(
            model_name='productbom',
            name='height_affected',
            field=models.BooleanField(default=False, verbose_name='تحت تأثیر ارتفاع'),
        ),
    ]
